version = 0.2
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Staging\""
image_repositories = []
confirm_changeset = true
s3_bucket = "cber028-unir"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
s3_prefix = "todo-list-aws-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
s3_bucket = "cber028-unir"
confirm_changeset = true

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_prefix = "todo-list-aws-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []

[Staging]
[Staging.deploy]
[Staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
s3_bucket = "cber028-unir"
s3_prefix = "todo-list-aws-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Staging\""
image_repositories = []
